version: '3.8'
services:
  backend:
    build: ./crowdsafe-backend
    ports:
      - '5000:5000'
    volumes:
      - ./crowdsafe-backend:/app
    environment:
      - FLASK_ENV=development
      - FIREBASE_CREDENTIALS=/app/serviceAccountKey.json
